from typing import List

from app.models.user_profile import UserProfile
from app.models.meal import MealCandidate, PlannedMeal, MealPlan


class MealAgent:
    def plan(
        self,
        profile: UserProfile,
        catalog: List[MealCandidate],
        history: List[MealPlan],
        target_day: str,
    ) -> MealPlan:
        safe_meals = self._filter_safe_meals(profile, catalog)
        ranked_meals = self._rank_meals(profile, safe_meals, history)

        selected_meals: list[dict] = []
        used_ids: set[str] = set()

        for item in ranked_meals:
            meal = item["meal"]
            if meal.id in used_ids:
                continue

            selected_meals.append(item)
            used_ids.add(meal.id)

            if len(selected_meals) >= profile.daily_meal_count:
                break

        planned_meals = [
            PlannedMeal(
                meal_type=self._resolve_meal_type(index),
                item_id=item["meal"].id,
                item_name=item["meal"].name,
                calories=item["meal"].calories,
                price=item["meal"].price,
                reason=item["reason"],
                score=item["score"],
            )
            for index, item in enumerate(selected_meals)
        ]

        total_calories = sum(meal.calories for meal in planned_meals)
        total_price = sum(meal.price for meal in planned_meals)

        return MealPlan(
            day=target_day,
            meals=planned_meals,
            total_calories=total_calories,
            total_price=total_price,
            notes="Meal plan generated by MealAgent v4 with budget-aware scoring",
        )

    def _filter_safe_meals(
        self,
        profile: UserProfile,
        catalog: List[MealCandidate],
    ) -> List[MealCandidate]:
        forbidden = {item.lower() for item in profile.forbidden_products}
        allergies = {item.lower() for item in profile.allergies}

        safe_meals: List[MealCandidate] = []

        for meal in catalog:
            if not meal.available:
                continue

            ingredients = {ingredient.lower() for ingredient in meal.ingredients}
            name_lower = meal.name.lower()

            if ingredients & allergies:
                continue

            if any(product in name_lower for product in forbidden):
                continue

            if ingredients & forbidden:
                continue

            safe_meals.append(meal)

        return safe_meals

    def _rank_meals(
        self,
        profile: UserProfile,
        meals: List[MealCandidate],
        history: List[MealPlan],
    ) -> List[dict]:
        likes = {item.lower() for item in profile.likes}
        dislikes = {item.lower() for item in profile.dislikes}
        recent_meal_ids = self._extract_recent_meal_ids(history, limit_days=3)

        ranked: List[dict] = []

        for meal in meals:
            meal_tokens = {
                meal.name.lower(),
                *(x.lower() for x in meal.ingredients),
                *(x.lower() for x in meal.tags),
            }

            score = 0
            reasons: list[str] = []

            like_matches = meal_tokens & likes
            dislike_matches = meal_tokens & dislikes

            if like_matches:
                bonus = len(like_matches) * 3
                score += bonus
                reasons.append(f"+{bonus} for likes match: {', '.join(sorted(like_matches))}")

            if dislike_matches:
                penalty = len(dislike_matches) * 2
                score -= penalty
                reasons.append(f"-{penalty} for dislikes match: {', '.join(sorted(dislike_matches))}")

            target_per_meal = profile.calorie_target / max(profile.daily_meal_count, 1)
            calorie_distance = abs(meal.calories - target_per_meal)
            calorie_penalty = int(calorie_distance / 100)
            score -= calorie_penalty
            reasons.append(
                f"-{calorie_penalty} for calorie distance ({meal.calories} vs target {int(target_per_meal)})"
            )

            if meal.id in recent_meal_ids:
                score -= 5
                reasons.append("-5 for recent repetition")

            if profile.budget_per_day is not None:
                target_per_meal_budget = profile.budget_per_day / max(profile.daily_meal_count, 1)
                budget_distance = max(0, meal.price - target_per_meal_budget)
                budget_penalty = int(budget_distance / 50)
                score -= budget_penalty
                reasons.append(
                    f"-{budget_penalty} for budget distance ({meal.price} vs target {target_per_meal_budget:.0f})"
                )

            ranked.append({
                "meal": meal,
                "score": score,
                "reason": "; ".join(reasons),
            })

        return sorted(ranked, key=lambda item: item["score"], reverse=True)

    def _extract_recent_meal_ids(
        self,
        history: List[MealPlan],
        limit_days: int = 3,
    ) -> set[str]:
        recent_ids: set[str] = set()

        recent_plans = history[-limit_days:]
        for plan in recent_plans:
            for meal in plan.meals:
                recent_ids.add(meal.item_id)

        return recent_ids

    def _resolve_meal_type(self, index: int) -> str:
        meal_types = ["breakfast", "lunch", "dinner", "snack"]
        if index < len(meal_types):
            return meal_types[index]
        return f"meal_{index + 1}"