from typing import List

from app.models.user_profile import UserProfile
from app.models.meal import MealCandidate, PlannedMeal, MealPlan


class MealAgent:
    def plan(
        self,
        profile: UserProfile,
        catalog: List[MealCandidate],
        history: List[MealPlan],
        target_day: str,
    ) -> MealPlan:
        safe_meals = self.get_safe_catalog(profile, catalog)
        ranked_meals = self._rank_meals(profile, safe_meals, history)

        selected_meals: list[dict] = []
        used_ids: set[str] = set()

        for item in ranked_meals:
            meal = item["meal"]
            if meal.id in used_ids:
                continue

            selected_meals.append(item)
            used_ids.add(meal.id)

            if len(selected_meals) >= profile.daily_meal_count:
                break

        planned_meals = [
            PlannedMeal(
                meal_type=self._resolve_meal_type(index),
                item_id=item["meal"].id,
                item_name=item["meal"].name,
                calories=item["meal"].calories,
                price=item["meal"].price,
                reason=item["reason"],
                score=item["score"],
            )
            for index, item in enumerate(selected_meals)
        ]

        total_calories = sum(meal.calories for meal in planned_meals)
        total_price = sum(meal.price for meal in planned_meals)

        return MealPlan(
            day=target_day,
            meals=planned_meals,
            total_calories=total_calories,
            total_price=total_price,
            notes="Meal plan generated by MealAgent v7 with catalog helpers",
        )

    def get_safe_catalog(
        self,
        profile: UserProfile,
        catalog: List[MealCandidate],
    ) -> List[MealCandidate]:
        return self._filter_safe_meals(profile, catalog)

    def _meal_tokens(self, meal: MealCandidate) -> set[str]:
        return {
            meal.name.lower(),
            *(x.lower() for x in meal.ingredients),
            *(x.lower() for x in meal.tags),
        }

    def _filter_safe_meals(
        self,
        profile: UserProfile,
        catalog: List[MealCandidate],
    ) -> List[MealCandidate]:
        forbidden = {item.lower() for item in profile.forbidden_products}
        allergies = {item.lower() for item in profile.allergies}
        dislikes = {item.lower() for item in profile.dislikes}

        safe_meals: List[MealCandidate] = []

        for meal in catalog:
            if not meal.available:
                continue

            ingredients = {ingredient.lower() for ingredient in meal.ingredients}
            name_lower = meal.name.lower()
            meal_tokens = self._meal_tokens(meal)

            if ingredients & allergies:
                continue

            if any(product in name_lower for product in forbidden):
                continue

            if ingredients & forbidden:
                continue

            if profile.dislike_mode == "hard" and (meal_tokens & dislikes):
                continue

            safe_meals.append(meal)

        return safe_meals

    def _rank_meals(
        self,
        profile: UserProfile,
        meals: List[MealCandidate],
        history: List[MealPlan],
    ) -> List[dict]:
        likes = {item.lower() for item in profile.likes}
        dislikes = {item.lower() for item in profile.dislikes}

        recent_meal_ids = self._extract_recent_meal_ids(history, limit_days=3)
        recent_meal_counts = self._extract_recent_meal_counts(history, limit_days=7)
        yesterday_meal_ids = self._extract_yesterday_meal_ids(history)

        ranked: List[dict] = []

        for meal in meals:
            meal_tokens = self._meal_tokens(meal)

            score = 0
            reasons: list[str] = []

            like_matches = meal_tokens & likes
            dislike_matches = meal_tokens & dislikes

            if like_matches:
                bonus = len(like_matches) * 3
                score += bonus
                reasons.append(f"+{bonus}: совпадение с likes ({', '.join(sorted(like_matches))})")

            if dislike_matches and profile.dislike_mode == "soft":
                penalty = len(dislike_matches) * 2
                score -= penalty
                reasons.append(f"-{penalty}: совпадение с dislikes ({', '.join(sorted(dislike_matches))})")

            target_per_meal = profile.calorie_target / max(profile.daily_meal_count, 1)
            calorie_distance = abs(meal.calories - target_per_meal)
            calorie_penalty = int(calorie_distance / 100)
            score -= calorie_penalty
            reasons.append(
                f"-{calorie_penalty}: отклонение по калориям ({meal.calories} vs target {int(target_per_meal)})"
            )

            if meal.id in recent_meal_ids:
                score -= 5
                reasons.append("-5: блюдо встречалось в последние 3 дня")

            if meal.id in yesterday_meal_ids:
                score -= 8
                reasons.append("-8: блюдо было вчера")

            repeat_count = recent_meal_counts.get(meal.id, 0)
            if repeat_count > 0:
                repeat_penalty = repeat_count * 3
                score -= repeat_penalty
                reasons.append(f"-{repeat_penalty}: частота повторов за 7 дней ({repeat_count})")

            if profile.budget_per_day is not None:
                target_per_meal_budget = profile.budget_per_day / max(profile.daily_meal_count, 1)
                budget_distance = max(0, meal.price - target_per_meal_budget)
                budget_penalty = int(budget_distance / 50)
                score -= budget_penalty
                reasons.append(
                    f"-{budget_penalty}: отклонение по бюджету ({meal.price} vs target {target_per_meal_budget:.0f})"
                )

            ranked.append({
                "meal": meal,
                "score": score,
                "reason": " | ".join(reasons),
            })

        return sorted(ranked, key=lambda item: item["score"], reverse=True)

    def _extract_recent_meal_ids(
        self,
        history: List[MealPlan],
        limit_days: int = 3,
    ) -> set[str]:
        recent_ids: set[str] = set()

        recent_plans = history[-limit_days:]
        for plan in recent_plans:
            for meal in plan.meals:
                recent_ids.add(meal.item_id)

        return recent_ids

    def _extract_recent_meal_counts(
        self,
        history: List[MealPlan],
        limit_days: int = 7,
    ) -> dict[str, int]:
        counts: dict[str, int] = {}
        recent_plans = history[-limit_days:]

        for plan in recent_plans:
            for meal in plan.meals:
                counts[meal.item_id] = counts.get(meal.item_id, 0) + 1

        return counts

    def _extract_yesterday_meal_ids(self, history: List[MealPlan]) -> set[str]:
        if not history:
            return set()

        last_plan = history[-1]
        return {meal.item_id for meal in last_plan.meals}

    def _resolve_meal_type(self, index: int) -> str:
        meal_types = ["Завтрак", "Обед", "Ужин", "Перекус"]
        if index < len(meal_types):
            return meal_types[index]
        return f"Приём пищи {index + 1}"