from app.models.user_profile import UserProfile
from app.models.meal import MealPlan
from app.models.order import OrderPlan, OrderItem


class OrderAgent:
    def build_order(
        self,
        profile: UserProfile,
        meal_plan: MealPlan,
        chosen_slot: str | None,
    ) -> OrderPlan:
        items: list[OrderItem] = []

        for meal in meal_plan.meals:
            items.append(
                OrderItem(
                    name=meal.item_name,
                    quantity=1,
                    source_id=meal.item_id,
                    replacement_options=[],
                )
            )

        return OrderPlan(
            provider="demo_delivery_provider",
            items=items,
            delivery_slot=chosen_slot,
            total_estimated_price=meal_plan.total_price,
            comment="Generated by OrderAgent v1",
        )